a=10
b=5
print("Value of a =",a)
print("Value of b =",b)
print("Value of a before swapping=",a)
print("Value of b beforem swapping=",b)
temp=a
a=b
b=temp
print("Value of a after swapping=",a)
print("Value of b after swapping=",b)
a=10
b=5
a=a+b
b=a-b
a=a-b
print("Value of a after swapping=",a)
print("Value of b after swapping=",b)

